IMPORTING THE DATA

In [1]:
import pandas as pd
df=pd.read_csv('HR-Employee-Attrition.csv')
print (df)

      Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales   
1      49        No  Travel_Frequently        279  Research & Development   
2      37       Yes      Travel_Rarely       1373  Research & Development   
3      33        No  Travel_Frequently       1392  Research & Development   
4      27        No      Travel_Rarely        591  Research & Development   
...   ...       ...                ...        ...                     ...   
1465   36        No  Travel_Frequently        884  Research & Development   
1466   39        No      Travel_Rarely        613  Research & Development   
1467   27        No      Travel_Rarely        155  Research & Development   
1468   49        No  Travel_Frequently       1023                   Sales   
1469   34        No      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  \
0       

In [2]:
df.shape

(1470, 35)

In [3]:
df.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   
4  ...                         4            80                 1   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   
4                  6                      3               3               2   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  
4                  2                        2                     2  

[5 rows x 35 columns]

CHECKING DATATYPES

In [4]:
df.dtypes

Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears   

ENCODING

In [5]:
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
df["Attrition"]=LE.fit_transform(df["Attrition"])
df["Department"]=LE.fit_transform(df["Department"])
df["EducationField"]=LE.fit_transform(df["EducationField"])
df["Gender"]=LE.fit_transform(df["Gender"])
df["JobRole"]=LE.fit_transform(df["JobRole"])
df["MaritalStatus"]=LE.fit_transform(df["MaritalStatus"])
df["Over18"]=LE.fit_transform(df["Over18"])
df["OverTime"]=LE.fit_transform(df["OverTime"])

DROPPING BUSINESS TRAVEL

In [6]:
df.drop('BusinessTravel',axis=1, inplace=True)

In [7]:
df.dtypes

Age                         int64
Attrition                   int32
DailyRate                   int64
Department                  int32
DistanceFromHome            int64
Education                   int64
EducationField              int32
EmployeeCount               int64
EmployeeNumber              int64
EnvironmentSatisfaction     int64
Gender                      int32
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobRole                     int32
JobSatisfaction             int64
MaritalStatus               int32
MonthlyIncome               int64
MonthlyRate                 int64
NumCompaniesWorked          int64
Over18                      int32
OverTime                    int32
PercentSalaryHike           int64
PerformanceRating           int64
RelationshipSatisfaction    int64
StandardHours               int64
StockOptionLevel            int64
TotalWorkingYears           int64
TrainingTimesLastYear       int64
WorkLifeBalanc

In [8]:
df.head()

Age  Attrition  DailyRate  Department  DistanceFromHome  Education  \
0   41          1       1102           2                 1          2   
1   49          0        279           1                 8          1   
2   37          1       1373           1                 2          2   
3   33          0       1392           1                 3          4   
4   27          0        591           1                 2          1   

   EducationField  EmployeeCount  EmployeeNumber  EnvironmentSatisfaction  \
0               1              1               1                        2   
1               1              1               2                        3   
2               4              1               4                        4   
3               1              1               5                        4   
4               3              1               7                        1   

   ...  RelationshipSatisfaction  StandardHours  StockOptionLevel  \
0  ...                         1             80                 0   
1  ...                         4             80                 1   
2  ...                         2             80                 0   
3  ...                         3             80                 0   
4  ...                         4             80                 1   

   TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
0                  8                      0                1               6   
1                 10                      3                3              10   
2                  7                      3                3               0   
3                  8                      3                3               8   
4                  6                      3                3               2   

   YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                   4                        0                     5  
1                   7                        1                     7  
2                   0                        0                     0  
3                   7                        3                     0  
4                   2                        2                     2  

[5 rows x 34 columns]

CHECKING CORRELATION

In [9]:
dfcor=df.corr()
dfcor

Age  Attrition  DailyRate  Department  \
Age                       1.000000  -0.159205   0.010661   -0.031882   
Attrition                -0.159205   1.000000  -0.056652    0.063991   
DailyRate                 0.010661  -0.056652   1.000000    0.007109   
Department               -0.031882   0.063991   0.007109    1.000000   
DistanceFromHome         -0.001686   0.077924  -0.004985    0.017225   
Education                 0.208034  -0.031373  -0.016806    0.007996   
EducationField           -0.040873   0.026846   0.037709    0.013720   
EmployeeCount                  NaN        NaN        NaN         NaN   
EmployeeNumber           -0.010145  -0.010577  -0.050990   -0.010895   
EnvironmentSatisfaction   0.010146  -0.103369   0.018355   -0.019395   
Gender                   -0.036311   0.029453  -0.011716   -0.041583   
HourlyRate                0.024287  -0.006846   0.023381   -0.004144   
JobInvolvement            0.029820  -0.130016   0.046135   -0.024586   
JobLevel                  0.509604  -0.169105   0.002966    0.101963   
JobRole                  -0.122427   0.067151  -0.009472    0.662431   
JobSatisfaction          -0.004892  -0.103481   0.030571    0.021001   
MaritalStatus            -0.095029   0.162070  -0.069586    0.056073   
MonthlyIncome             0.497855  -0.159840   0.007707    0.053130   
MonthlyRate               0.028051   0.015170  -0.032182    0.023642   
NumCompaniesWorked        0.299635   0.043494   0.038153   -0.035882   
Over18                         NaN        NaN        NaN         NaN   
OverTime                  0.028062   0.246118   0.009135    0.007481   
PercentSalaryHike         0.003634  -0.013478   0.022704   -0.007840   
PerformanceRating         0.001904   0.002889   0.000473   -0.024604   
RelationshipSatisfaction  0.053535  -0.045872   0.007846   -0.022414   
StandardHours                  NaN        NaN        NaN         NaN   
StockOptionLevel          0.037510  -0.137145   0.042143   -0.012193   
TotalWorkingYears         0.680381  -0.171063   0.014515   -0.015762   
TrainingTimesLastYear    -0.019621  -0.059478   0.002453    0.036875   
WorkLifeBalance          -0.021490  -0.063939  -0.037848    0.026383   
YearsAtCompany            0.311309  -0.134392  -0.034055    0.022920   
YearsInCurrentRole        0.212901  -0.160545   0.009932    0.056315   
YearsSinceLastPromotion   0.216513  -0.033019  -0.033229    0.040061   
YearsWithCurrManager      0.202089  -0.156199  -0.026363    0.034282   

                          DistanceFromHome  Education  EducationField  \
Age                              -0.001686   0.208034       -0.040873   
Attrition                         0.077924  -0.031373        0.026846   
DailyRate                        -0.004985  -0.016806        0.037709   
Department                        0.017225   0.007996        0.013720   
DistanceFromHome                  1.000000   0.021042        0.002013   
Education                         0.021042   1.000000       -0.039592   
EducationField                    0.002013  -0.039592        1.000000   
EmployeeCount                          NaN        NaN             NaN   
EmployeeNumber                    0.032916   0.042070       -0.002516   
EnvironmentSatisfaction          -0.016075  -0.027128        0.043163   
Gender                           -0.001851  -0.016547       -0.002504   
HourlyRate                        0.031131   0.016775       -0.021941   
JobInvolvement                    0.008783   0.042438       -0.002655   
JobLevel                          0.005303   0.101589       -0.044933   
JobRole                          -0.001015   0.004236        0.015599   
JobSatisfaction                  -0.003669  -0.011296       -0.034401   
MaritalStatus                    -0.014437   0.004053        0.014420   
MonthlyIncome                    -0.017014   0.094961       -0.041070   
MonthlyRate                       0.027473  -0.026084       -0.027182   
NumCompaniesWorked               -0.029251   0.126

DROPPING THREE COLUMNS AS THEY HAVE NO CORRELATION

In [10]:
df.drop('EmployeeCount',axis=1, inplace=True)
df.drop('Over18',axis=1, inplace=True)
df.drop('StandardHours',axis=1, inplace=True)

In [11]:
df.head()

Age  Attrition  DailyRate  Department  DistanceFromHome  Education  \
0   41          1       1102           2                 1          2   
1   49          0        279           1                 8          1   
2   37          1       1373           1                 2          2   
3   33          0       1392           1                 3          4   
4   27          0        591           1                 2          1   

   EducationField  EmployeeNumber  EnvironmentSatisfaction  Gender  ...  \
0               1               1                        2       0  ...   
1               1               2                        3       1  ...   
2               4               4                        4       1  ...   
3               1               5                        4       0  ...   
4               3               7                        1       1  ...   

   PerformanceRating  RelationshipSatisfaction  StockOptionLevel  \
0                  3                         1                 0   
1                  4                         4                 1   
2                  3                         2                 0   
3                  3                         3                 0   
4                  3                         4                 1   

   TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
0                  8                      0                1               6   
1                 10                      3                3              10   
2                  7                      3                3               0   
3                  8                      3                3               8   
4                  6                      3                3               2   

   YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                   4                        0                     5  
1                   7                        1                     7  
2                   0                        0                     0  
3                   7                        3                     0  
4                   2                        2                     2  

[5 rows x 31 columns]

SPLITTING INTO X AND Y

In [12]:
x=df.drop("Attrition",axis=1)
y=df["Attrition"]
x.head()

Age  DailyRate  Department  DistanceFromHome  Education  EducationField  \
0   41       1102           2                 1          2               1   
1   49        279           1                 8          1               1   
2   37       1373           1                 2          2               4   
3   33       1392           1                 3          4               1   
4   27        591           1                 2          1               3   

   EmployeeNumber  EnvironmentSatisfaction  Gender  HourlyRate  ...  \
0               1                        2       0          94  ...   
1               2                        3       1          61  ...   
2               4                        4       1          92  ...   
3               5                        4       0          56  ...   
4               7                        1       1          40  ...   

   PerformanceRating  RelationshipSatisfaction  StockOptionLevel  \
0                  3                         1                 0   
1                  4                         4                 1   
2                  3                         2                 0   
3                  3                         3                 0   
4                  3                         4                 1   

   TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
0                  8                      0                1               6   
1                 10                      3                3              10   
2                  7                      3                3               0   
3                  8                      3                3               8   
4                  6                      3                3               2   

   YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                   4                        0                     5  
1                   7                        1                     7  
2                   0                        0                     0  
3                   7                        3                     0  
4                   2                        2                     2  

[5 rows x 30 columns]

In [13]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Attrition, dtype: int32

In [14]:
df['Attrition'].value_counts()

0    1233
1     237
Name: Attrition, dtype: int64

TARGET VALUE HAS UNEQUAL VALUES SO APPLYING SMOTE

In [18]:
import numpy as np 

from imblearn.over_sampling import SMOTE

x_sample, y_sample = SMOTE().fit_resample(x, y.values.ravel())





 SCALING

In [20]:
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()
scaled = mms.fit_transform(df)
print(scaled)

[[0.54761905 1.         0.71581961 ... 0.22222222 0.         0.29411765]
 [0.73809524 0.         0.12670007 ... 0.38888889 0.06666667 0.41176471]
 [0.45238095 1.         0.90980673 ... 0.         0.         0.        ]
 ...
 [0.21428571 0.         0.03793844 ... 0.11111111 0.         0.17647059]
 [0.73809524 0.         0.65926986 ... 0.33333333 0.         0.47058824]
 [0.38095238 0.         0.37652112 ... 0.16666667 0.06666667 0.11764706]]


TRAIN TEST SPLIT

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=0) 

BUILDING MODELS

In [23]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [24]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,

In [25]:
from sklearn import metrics
print('The accuracy of Random Forest Classification is: ', metrics.accuracy_score(y_pred, y_test))

The accuracy of Random Forest Classification is:  0.8477366255144033


In [26]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [27]:
cm

array([[401,   6],
       [ 68,  11]], dtype=int64)

DTC

In [28]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [29]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,

In [30]:
from sklearn import metrics
print('The accuracy of Random Forest Classification is: ', metrics.accuracy_score(y_pred, y_test))

The accuracy of Random Forest Classification is:  0.8065843621399177


In [31]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [32]:
cm

array([[362,  45],
       [ 49,  30]], dtype=int64)

In [ ]:
We are getting 84% accuracy in random forsest so random forest is the best model